Added another one db
avelino/awesome-go pull request #3433
Opened 2021-01-06 23:30 UTC by cheshir

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/cheshir/ttlcache
- pkg.go.dev: https://pkg.go.dev/github.com/cheshir/ttlcache
- goreportcard.com: https://goreportcard.com/report/github.com/cheshir/ttlcache
- coverage service link: https://codecov.io/gh/cheshir/ttlcache

Very good coverage: 100%

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [+] I have added my package in alphabetical order.
- [+] I have an appropriate description with correct grammar.
- [+] I know that this package was not listed before.
- [+] I have added pkg.go.dev link to the repo and to my pull request.
- [+] I have added coverage service link to the repo and to my pull request.
- [+] I have added goreportcard link to the repo and to my pull request.
- [+] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

2021-01-06 23:33 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

2021-01-07 08:34 UTC, phanirithvij requested changes

2021-01-07 08:34 UTC, phanirithvij commented on README.md
> +* [ttlcache](https://github.com/cheshir/ttlcache) – In-memory key value storage with TTL for each record.
Use `-` instead of [`–`](https://www.google.com/search?q=en+dash)

2021-01-07 09:06 UTC, cheshir commented
@avelino Check it please.

2021-01-13 12:39 UTC, merged