Take advantage of the new README features
avelino/awesome-go pull request #3558
Opened 2021-04-06 02:11 UTC by Joakker

Closes #3550 
This PR takes advantage of the new Github features for auto generating the table of contents. It also adds emojis to every header in the document to make them distinguishable from one another

2021-04-06 02:11 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

2021-04-06 02:17 UTC, Joakker commented
I should also mention that the headers don't exactly map out to the emojis' meanings, since some of them were a bit too specific to find a suitable one, and some of them are duplicated, but in general, I tried to make the emoji be at least tangentially related in meaning to the title they correspond to.

2021-04-06 22:00 UTC, avelino requested changes

2021-04-06 22:00 UTC, avelino commented on README.md
The content list must be exist, it will be used on the site awesome-go.com

2021-04-06 22:51 UTC, Joakker commented
There, this seems to work well

2021-04-07 00:00 UTC, avelino requested changes
Put the emoji in the prefix is breaking the test alphabetically, we have put at the end of the title

Check Travis-CI: https://travis-ci.com/github/avelino/awesome-go/builds/222335165

2021-04-09 15:30 UTC, avelino commented
@Joakker many links are broken, are you aware of this?

Can you keep working on this change?

2021-04-09 18:39 UTC, Joakker commented
I can. But most of the links work on my end, so I don't know what is going on

2021-05-03 00:13 UTC, closed without merging