Add Plik to the Other Software section
avelino/awesome-go pull request #3916
Opened 2021-11-24 15:25 UTC by camathieu

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/root-gg/plik/tree/master
- live demo : https://plik.root.gg/#/
- pkg.go.dev: https://pkg.go.dev/github.com/root-gg/plik
- goreportcard.com: https://goreportcard.com/report/github.com/root-gg/plik
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):

Can't get any of them to work properly but coverage is displayed in every build :
https://github.com/root-gg/plik/runs/4300158864

ok  	github.com/root-gg/plik/plik	10.153s	coverage: 90.1% of statements
ok  	github.com/root-gg/plik/server/common	50.332s	coverage: 87.0% of statements
ok  	github.com/root-gg/plik/server/context	0.050s	coverage: 25.3% of statements (automatically generated accessors)
ok  	github.com/root-gg/plik/server/data/file	0.046s	coverage: 89.5% of statements
ok  	github.com/root-gg/plik/server/data/stream	0.084s	coverage: 100.0% of statements
ok  	github.com/root-gg/plik/server/data/testing	0.040s	coverage: 96.4% of statements
ok  	github.com/root-gg/plik/server/handlers	65.720s	coverage: 83.9% of statements
ok  	github.com/root-gg/plik/server/metadata	8.501s	coverage: 82.1% of statements
ok  	github.com/root-gg/plik/server/middleware	0.298s	coverage: 90.2% of statements
ok  	github.com/root-gg/plik/server/server	2.103s	coverage: 75.9% of statements

Tests are also run against compatible backends using Docker images (see the test-backends step)

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x ] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request. (see above)
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:
YOU are awesome :)

2021-11-24 15:27 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

2021-11-26 06:53 UTC, Bonsland commented
To read the article in its full, please click the link below:

https://vuuzletvph.com/what-is-the-secret-of-nft-tokens-and-why-they-are-bought-for-millions-of-dollars/

(You will be automatically redirected to the page once clicked/tapped)



What is the secret of NFT tokens and why they are bought for millions of dollars - Vuuzle.TV Philippines
https://vuuzletvph.com
To read the article in its full, please click the link below:

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

(You will be automatically redirected to the page once clicked/tapped)



HEADS UP: VUCO Bounty Programs are coming your way! - Vuuzle.TV Philippines
https://vuuzletvph.com
Cryptocaptrades
www.cryptocaptrades.com
Vuuzle Media Corp Limited sets into motion a whole blockchain ecology that can be explored in one application, the Cryptocaptrades.

Transactions made easy, use your
money with confidence
By using Cryptocaptrades, most kinds of cryptocurrency available in the market are now one tap away. Through this innovative app, you are now able to store, send, buy or sell existing cryptocurrencies. Cryptocaptrades is also a carrier for diverse third-party DAPPs.

2022-01-28 21:05 UTC, avelino requested changes
merge to upstream (`main` branch)

2022-01-28 21:38 UTC, avelino approved these changes

2022-01-28 21:39 UTC, merged