Update README.md
avelino/awesome-go pull request #3927
Opened 2021-12-01 21:49 UTC by rtviii

Added the Solana RPC implementation in Go to the Blockchains section. This one's going to be important ;)

2021-12-01 21:49 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

2021-12-08 05:05 UTC, phanirithvij requested changes
Please follow the pull request template after reading the contribution guidelines https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

2021-12-09 10:01 UTC, Khalid55511 approved these changes

2021-12-18 06:00 UTC, phanirithvij commented
@rtviii ping.

2021-12-18 19:41 UTC, rtviii commented
@phanirithvij hey, sorry. moved to the alphabetical order and added appropriate links! take a look, thanks!!:)

2021-12-19 03:21 UTC, phanirithvij requested changes

2021-12-19 03:21 UTC, phanirithvij commented on README.md
> +* [solana-go](https://github.com/gagliardetto/solana-go) - Go library to interface with Solana JSON RPC and WebSocket interfaces.
- Golint has many exported functions with no comments
- No coverage report in tests, and I see lots of `no test files` in the repo's test GitHub action.

- I'll see if I can test the coverage locally in a few hours

2021-12-19 03:28 UTC, phanirithvij commented on README.md
> +* [gossamer](https://github.com/ChainSafe/gossamer) - A Go implementation of the Polkadot Host
```suggestion
* [gossamer](https://github.com/ChainSafe/gossamer) - A Go implementation of the Polkadot Host.
```

2021-12-28 00:26 UTC, Khalid55511 approved these changes

2021-12-28 05:31 UTC, phanirithvij approved these changes

2021-12-28 05:31 UTC, merged