add artifact web framework
avelino/awesome-go pull request #4072
Opened 2022-03-02 08:35 UTC by Shipu

> Please check if what you want to add to awesome-go list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): [https://github.com/Shipu/artifact](https://github.com/Shipu/artifact)
- pkg.go.dev: https://pkg.go.dev/github.com/Shipu/artifact
- goreportcard.com: https://goreportcard.com/report/github.com/shipu/artifact

**Note:** _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! 👍

2022-03-02 15:08 UTC, avelino requested changes
did you see the automatic comment that is missing the coverage link?

apart from this item, review:
- golint
- your package is licensed under which license?

2022-03-05 20:31 UTC, Cynthia1235566 approved these changes

2022-03-05 20:49 UTC, Cynthia1235566 commented
> did you see the automatic comment that is missing the coverage link?
> 
> 
> 
> apart from this item, review:
> 
> - golint
> 
> - your package is licensed under which license?

Hello

2022-03-05 23:15 UTC, Cynthia1235566 approved these changes

2022-03-29 00:22 UTC, closed without merging