Add OWASP Coraza to the list
avelino/awesome-go pull request #4153
Opened 2022-03-30 19:59 UTC by jptosso

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/corazawaf/coraza
- pkg.go.dev:https://pkg.go.dev/github.com/corazawaf/coraza/v2
- goreportcard.com: https://goreportcard.com/report/github.com/corazawaf/coraza/v2
- coverage service link: https://sonarcloud.io/project/overview?id=jptosso_coraza-waf

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

2022-03-30 20:00 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

2022-03-30 20:11 UTC, jptosso commented
> Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.
> 
> Automation body links content check:
> 
> * godoc.org or pkg.go.dev: True
> * goreportcard.com: True
> * coverage: False
> 
> > your project is about to be approved, it's under revision, _it may take a few days_

Coverage is over 83%: https://sonarcloud.io/project/overview?id=jptosso_coraza-waf

2022-03-31 10:25 UTC, phanirithvij requested changes

2022-03-31 10:25 UTC, phanirithvij commented on README.md
> +- [OWASP Coraza](https://github.com/corazawaf/coraza) - Enterprise-ready, modsecurity and OWASP CRS compatible WAF library.
```suggestion
- [Coraza](https://github.com/corazawaf/coraza) - Enterprise-ready, modsecurity and OWASP CRS compatible WAF library.
```

2022-03-31 10:27 UTC, merged