Add iWF
avelino/awesome-go pull request #4749
Opened 2023-02-15 23:59 UTC by longquanzheng

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/indeedeng/iwf
- pkg.go.dev: https://pkg.go.dev/github.com/indeedeng/iwf
- goreportcard.com: https://goreportcard.com/report/github.com/indeedeng/iwf
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): WIP in https://github.com/indeedeng/iwf/pull/184 

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.
   -  NOTE: we have done this before knowing this requirement here, but will make sure we will not do this in the future :( 

Thanks for your PR, you're awesome! :+1:

2023-02-16 00:05 UTC, avelino commented
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

2023-11-24 05:29 UTC, skydiver1980 approved these changes

2024-08-13 08:22 UTC, yassinebenaid requested changes

2024-08-13 08:22 UTC, yassinebenaid commented on README.md
> +- [iWF](https://github.com/indeedeng/iwf) - iWF is an all-in-one platform for developing long-running business processes. It offers a convenient abstraction for utilizing databases, ElasticSearch, me
- The coverage is 72%. The minimum required threshold is 80%.

2024-09-23 08:29 UTC, yassinebenaid approved these changes

2024-09-23 08:29 UTC, merged