Add ergo-services/ergo
avelino/awesome-go pull request #4901
Opened 2023-05-29 01:13 UTC by Nezteb

This was attempted in 2020 but the PR was closed. https://github.com/avelino/awesome-go/pull/2998

**Please provide package links to:**

- repo link: https://github.com/ergo-services/ergo
- pkg.go.dev: https://pkg.go.dev/github.com/ergo-services/ergo
- goreportcard.com: https://goreportcard.com/report/github.com/ergo-services/ergo
- coverage service link: N/A

**Make sure that you've checked the boxes below that apply before you submit PR.**

- [X] The package has been added to the list in alphabetical order.
- [X] The package has an appropriate description with correct grammar.
- [X] As far as I know, the package has not been listed here before.
- [X] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [X] The repo documentation has a goreportcard link.
- [X] The repo has a version-numbered release and a go.mod file.
- [X] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [X] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [X] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

2023-05-29 02:10 UTC, avelino requested changes
https://github.com/avelino/awesome-go/pull/2998#pullrequestreview-374422693

What we asked for in this code review has not been solved so far, that is why it was not accepted

2023-05-29 03:06 UTC, Nezteb commented
@avelino Ahhh, got it.

I've made corresponding items for each issue:
- https://github.com/ergo-services/ergo/pull/158
- https://github.com/ergo-services/ergo/issues/159

2023-05-29 21:04 UTC, bumpvcc approved these changes

2023-11-24 04:51 UTC, skydiver1980 approved these changes

2024-09-18 13:49 UTC, closed without merging

2024-09-18 13:49 UTC, yassinebenaid commented
Project is already listed. In fact, `ergo` is the first on the list.