Added m-way trie algorithms "bits" of sop library under the "Data Str…
avelino/awesome-go pull request #5110
Opened 2023-11-20 07:07 UTC by grecinto

…uctures->Trees" section.

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):
- pkg.go.dev:
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [ ] The package has been added to the list in alphabetical order.
- [ ] The package has an appropriate description with correct grammar.
- [ ] As far as I know, the package has not been listed here before.
- [ ] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [ ] The repo documentation has a goreportcard link.
- [ ] The repo has a version-numbered release and a go.mod file.
- [ ] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [ ] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

Thanks for your PR, you're awesome! :+1:

2023-11-20 07:10 UTC, grecinto commented
Please feel free to share knowledge about the following as this is my first time contributing, thanks much, 'appreciated:
godoc.org or pkg.go.dev
goreportcard.com
coverage

2023-11-24 05:17 UTC, skydiver1980 approved these changes

2024-02-12 20:16 UTC, grecinto commented
Any idea when this will be approved? Thanks.

2024-03-09 15:51 UTC, phanirithvij commented on README.md
> +optimized.
Fix this please

2024-03-09 15:52 UTC, phanirithvij requested changes
The line got split could you fix it.

2026-01-04 05:35 UTC, Jason-123-cyber requested changes
vfd

2026-01-04 18:56 UTC, Jason-123-cyber approved these changes
YAY!

2026-06-22 16:02 UTC, closed without merging