Add failsafe-go
avelino/awesome-go pull request #5245
Opened 2024-03-13 05:20 UTC by jhalterman

## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [ ] forge link (github.com, gitlab.com, etc): https://github.com/failsafe-go/failsafe-go
- [ ] pkg.go.dev: https://pkg.go.dev/github.com/failsafe-go/failsafe-go
- [ ] goreportcard.com: https://goreportcard.com/report/github.com/failsafe-go/failsafe-go
- [ ] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/failsafe-go/failsafe-go

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.
- [ ] I removed the following packages around my addition: (please give a short reason for each removal)

Thanks for your PR, you're awesome! :sunglasses:

2024-03-13 12:00 UTC, wobondar requested changes

2024-03-13 12:00 UTC, wobondar commented on README.md
> +- [Failsafe-go](https://failsafe-go.dev/) - Fault tolerance and resilience patterns for Go.
Accordingly to [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md):
> the link added to `README.md` is the same as the link to the repository mentioned in the body of the PR.

The link should be https://github.com/failsafe-go/failsafe-go, as mentioned in the PR body.

2024-03-13 17:10 UTC, wobondar approved these changes
Thanks!

2024-06-25 03:30 UTC, merged

2024-06-25 03:30 UTC, phanirithvij commented
Apologies for the late merge.